version: '3.8'

services:

  react:
    container_name: react
    build:
      context: .
      dockerfile: ./conf/react/Dockerfile
      target: prod
    env_file: .env
    ports:
     - 80:80
    depends_on:
      - "django"