version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: Build Docker
          command: docker-compose -f "docker-compose.yml" up -d --build
      - run:
          name: Flake8
          command: docker exec django tox -e flake8
      - run:
          name: Black
          command: docker exec django tox -e black       
      - run:
          name: ESLint
          command: docker exec react yarn lint         
      - run:
          name: Test polls
          command: docker exec django pytest --cov-report term-missing --cov=polls --ds=mysite3.settings