# Generated by Django 4.0.4 on 2022-05-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
