# Generated by Django 3.2.9 on 2021-11-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_auto_20211123_0738"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
