# Generated by Django 3.2.9 on 2021-11-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_auto_20211124_2112"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="id",
            new_name="pkid",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="id",
            new_name="pkid",
        ),
    ]
