# Generated by Django 3.2.9 on 2021-11-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_auto_20211124_2126"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="pkid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="pkid",
            new_name="id",
        ),
    ]
