name: pull request

on: pull_request

env:
  CACHE_IMAGE: riffraffer/docker-ci-cache
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Log in to docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker images
        run: docker-compose -f "docker-compose.yml" up -d --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Push to docker hub
        run: docker push latest

      - name: Flake8
        if: always()
        run: docker exec django tox -e flake8

      - name: Black
        if: always()
        run: docker exec django tox -e black

      - name: ESLint
        if: always()
        run: docker exec react yarn lint

      - name: Test mysite3
        if: always()
        run: docker exec -django pytest --cov-report term-missing --cov=mysite3 --ds=mysite3.settings

      - name: Test polls
        if: always()
        run: docker exec -django pytest --cov-report term-missing --cov=polls --ds=mysite3.settings

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
