name: pull request

on: pull_request

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      if: always()
      uses: actions/checkout@v1

    - name: Make envfile
      if: always()
      run: |
        touch .env
        echo DB_NAME=postgres >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD}} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_HOST=postgres >> .env
        echo DB_PORT=5432 >> .env
        echo APP_SERVER=uwsgi >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo SIGNING_KEY=${{ secrets.SIGNING_KEY }} >> .env
        echo DEBUG=0 >> .env
        cat .env

    - name: Start containers
      if: always()
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Make Migrations
      if: always()
      run: docker exec django python manage.py makemigrations

    - name: Migrate
      if: always()
      run: docker exec django python manage.py migrate

    - name: Make Migrations Polls
      if: always()
      run: docker exec django python manage.py makemigrations accounts

    - name: Migrate Polls
      if: always()
      run: docker exec django python manage.py migrate

    - name: Flake8
      if: always()
      run: docker exec -u root django tox -e flake8

    - name: Black
      if: always()
      run: docker exec -u root django tox -e black

    - name: ESLint
      if: always()
      run: docker exec react yarn lint

    - name: Test polls
      if: always()
      run: docker exec -u root django tox -e pytest

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
