name: pull request

on: pull_request

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Flake8
      if: always()
      run: docker exec django tox -e flake8

    - name: Black
      if: always()
      run: docker exec django tox -e black

    - name: ESLint
      if: always()
      run: docker exec react yarn lint

    - name: Test mysite3
      if: always()
      run: docker exec -django pytest --cov-report term-missing --cov=mysite3 --ds=mysite3.settings

    - name: Test polls
      if: always()
      run: docker exec -django pytest --cov-report term-missing --cov=polls --ds=mysite3.settings

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
